name: Test

on:
  pull_request:

  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read # we just need to checkout the repo

jobs:
  test:
    name: Test

    timeout-minutes: 45

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20.x, 24.x]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        run: |
          npm ci
          npx lerna bootstrap
        shell: bash

      - name: Run Tests
        run: npm run test -- --stream
        shell: bash
